{
 "title": "Customer Workload",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "[LOGS] entries / message bytes pushed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Log entries pushed (total)" }
   ],
   "targets": [
    {
     "expr": "sum(counter_log_entries_pushed)",
     "legendFormat": "Log entries pushed"
    },
    {
     "expr": "sum(counter_log_message_bytes_pushed)",
     "legendFormat": "Bytes pushed"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_sent_batch_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "[LOGS] nodejs_active_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (nodejs_active_requests)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_shards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_remote_storage_shards"
    },
    {
     "expr": "prometheus_remote_storage_shards_max"
    },
    {
     "expr": "prometheus_remote_storage_shards_min"
    },
    {
     "expr": "prometheus_remote_storage_shards_desired"
    }
   ]
  },
  {
   "title": "[LOGS] nodejs_eventloop_lag (p50, p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p50_seconds"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage_sent_batch_duration_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "prometheus_remote_storage samples",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_succeeded_samples_total[5m]))",
     "legendFormat": "succeeded_samples_total"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_failed_samples_total[5m]))",
     "legendFormat": "failed_samples_total"
    },
    {
     "expr": "sum(prometheus_remote_storage_pending_samples)",
     "legendFormat": "pending_samples"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_retried_samples_total[5m]))",
     "legendFormat": "retried_samples_total"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_dropped_samples_total[5m]))",
     "legendFormat": "dropped_samples_total"
    }
   ]
  },
  {
   "title": "Queue Length / % Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_notifications_queue_length"
    },
    {
     "expr": "prometheus_notifications_queue_length / prometheus_notifications_queue_capacity",
     "legendFormat": "% capacity used"
    }
   ]
  },
  {
   "title": "prometheus_http_request_duration_seconds_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_http_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "prometheus_sd_kubernetes_events_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_sd_kubernetes_events_total"
    }
   ]
  },
  {
   "title": "prometheus_target_scrape_pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_scrape_pools_failed_total"
    },
    {
     "expr": "prometheus_target_scrape_pools_total"
    }
   ]
  },
  {
   "title": "prometheus_target_metadata_cache_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_metadata_cache_bytes"
    }
   ]
  }
 ]
}