{
 "title": "DD API / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tenant", "label": "Tenant", "query": "default, system" },
   { "name": "timewindow", "label": "Time window width", "query": "1m, 2m, 3m, 4m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "/api/v1/series, POSTs, rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(dd_api_request_duration_seconds_count{job=\"$tenant-tenant.dd-api\",method=\"POST\",route=\"api_v1_series\"}[$timewindow]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "API container CPU util (%) (mean over $timewindow)",
   "type": "graph",
   "description": "100 % is one CPU core",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU util [%]" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{namespace=\"$tenant-tenant\", container=\"dd-api\"}[$timewindow])*100)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "/api/v1/series, 2xx-acked POSTs, request duration, event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (le) (rate(dd_api_request_duration_seconds_bucket{job=\"$tenant-tenant.dd-api\",method=\"POST\",status_code=~\"200|202|204\",route=\"api_v1_series\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API container mem (WSS)",
   "type": "graph",
   "description": "For context see https://www.bwplotka.dev/2019/golang-memory-monitoring/",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "WSS" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$tenant-tenant\", container=\"dd-api\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}