{
 "title": "Loki / Overview",
 "description": "Loki end-to-end overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*cortex.*\"}, namespace)"
    }
   },
   { "name": "timewindow", "label": "Time window width", "query": "1m, 2m, 3m, 4m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "API proxy /loki/api/v1/push, POSTs, rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_api_proxy_request_duration_seconds_count{job=\"$tenant-tenant.loki-api\",method=\"POST\",route=\"loki_api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "API proxy, /loki/api/v1/query[_range], 200-acked GETs, total request processing duration, event rate [1/s] ()",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(loki_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.loki-api\",method=\"GET\",status_code=\"200\",route=~\"loki_api_v1_query_.*\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ingester CPU util (%), all tenants ($timewindow mean)",
   "type": "graph",
   "description": "100 % is one CPU core",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU util [%]" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{namespace=\"loki\", container=\"ingester\"}[$timewindow])*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API proxy, /loki/api/v1/push, 204-acked POSTs, request duration, event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (le) (rate(loki_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.loki-api\",method=\"POST\",status_code=\"204\",route=\"loki_api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API proxy /loki/api/v1/query[_range]|loki_api_v1_tail, GETs, rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (route, status_code) (rate(loki_api_proxy_request_duration_seconds_count{job=\"$tenant-tenant.loki-api\", method=\"GET\", route=~\"loki_api_v1_query.*|loki_api_v1_tail\"}[$timewindow]))"
    }
   ]
  },
  {
   "title": "ingester mem (WSS), all tenants",
   "type": "graph",
   "description": "For context see https://www.bwplotka.dev/2019/golang-memory-monitoring/",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes", "label": "WSS" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"loki\", container=\"ingester\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "distributor: tenant: $tenant, ingest rate before rejection (timewindow mean)",
   "type": "graph",
   "description": "the counter is increased while reading the request body, before validation, and before passing things on to the ingester.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "entry rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{tenant=\"$tenant\"}[$timewindow]))",
     "legendFormat": "log entry rate"
    },
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{tenant=\"$tenant\"}[$timewindow]))",
     "legendFormat": "byte rate"
    }
   ]
  },
  {
   "title": "ingester: total data rate stored in chunks, tenant: $tenant ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "Bps", "label": "data rate [Bytes/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total{tenant=\"$tenant\"}[$timewindow]))",
     "legendFormat": "stored byte rate"
    }
   ]
  },
  {
   "title": "distributor CPU util (%), all tenants ($timewindow mean)",
   "type": "graph",
   "description": "100 % is one CPU core",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "CPU util [%]" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{namespace=\"loki\", container=\"distributor\"}[$timewindow])*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "distributor: all tenants, log entry ingest rate, before rejection ($timewindow mean)",
   "type": "graph",
   "description": "the counter is increased while reading the request body, before validation, and before passing things on to the ingester.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "entry rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total[$timewindow]))",
     "legendFormat": "all tenants"
    },
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[$timewindow]))"
    }
   ]
  },
  {
   "title": "Total number of chunks in memory, all tenants",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (loki_ingester_memory_chunks{job=\"loki.ingester\"})"
    }
   ]
  },
  {
   "title": "distributor mem (WSS) per node",
   "type": "graph",
   "description": "For context see https://www.bwplotka.dev/2019/golang-memory-monitoring/",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "WSS" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"loki\", container=\"distributor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "distributor, all tenants, POSTs only, HTTP response rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_request_duration_seconds_count{job=\"loki.distributor\", method=\"POST\"}[$timewindow]))"
    }
   ]
  },
  {
   "title": "distributor, all tenants, ingester append failure rate ($timewindow mean)",
   "type": "graph",
   "description": "ingester append failure rate is measured in the distributor",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "error rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_ingester_append_failures_total[$timewindow]))"
    }
   ]
  },
  {
   "title": "ingester flush queue length per instance (all tenants)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "queue length" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_flush_queue_length{job=\"loki.ingester\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ingester: rate of stored chunks, all tenants ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "chunks / sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunks_stored_total[$timewindow]))",
     "legendFormat": "stored byte rate"
    }
   ]
  },
  {
   "title": "loki_ingester_chunk_size_bytes: distribution of chunk sizes when flushed, ALL tenants, , event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum  by (le) (rate(loki_ingester_chunk_size_bytes_bucket{job=\"loki.ingester\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "loki_logql_querystats_downloaded_chunk_total (what does this _really_ mean?)",
   "type": "graph",
   "description": "What does this metric _really_ mean?",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_logql_querystats_downloaded_chunk_total[$timewindow]))"
    }
   ]
  }
 ]
}