{
 "title": "Looker (Loki API client)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "uptime/seconds" }
   ],
   "targets": [
    {
     "expr": "gauge_uptime{job=\"looker\"}",
     "legendFormat": "uptime {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "write/read cycles performed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "counter_rw_cycles{job=\"looker\"}",
     "legendFormat": "{{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "all lookers, postWithRetry duration (upon success), event rate [1/s]",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (le) (rate(duration_post_with_retry_seconds_bucket[30s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET HTTP response rate by status code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (looker_invocation_id, statuscode) (rate(counter_get_responses{job=\"looker\"}[30s]))",
     "legendFormat": "{{statuscode}}, {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "POST HTTP  request body size (gauge, last seen)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "request size" }
   ],
   "targets": [
    {
     "expr": "gauge_last_http_request_body_size_bytes",
     "legendFormat": "{{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "POST HTTP response rate by status code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (looker_invocation_id, statuscode) (rate(counter_post_responses{job=\"looker\"}[30s]))",
     "legendFormat": "{{statuscode}}, {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "sample push rate (log entries or metric samples)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "rate(counter_log_entries_pushed{job=\"looker\"}[30s])",
     "legendFormat": "{{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "rate of transient errors during POST",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "rate(counter_post_non_http_errors{job=\"looker\"}[30s])",
     "legendFormat": " {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "NodeJS process CPU utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent", "label": "CPU util" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"looker\"}[30s])*100",
     "legendFormat": "{{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "rate of transient errors during GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "rate(counter_get_non_http_errors{job=\"looker\"}[30s])",
     "legendFormat": " {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "NodeJS event loop lag max and mean",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_max_seconds{job=\"looker\"}",
     "legendFormat": "max {{looker_invocation_id}}"
    },
    {
     "expr": "nodejs_eventloop_lag_mean_seconds{job=\"looker\"}",
     "legendFormat": "mean {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "rate of unexpected query results",
   "type": "graph",
   "description": "unexpected query results (communicated in an HTTP success response) result in a retrying loop. If a retry succeeds then looker does not crash. This counter keeps track of every unexpected query result (such as unexpected number of entries in a query result).",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "rate(counter_unexpected_query_results{job=\"looker\"}[30s])",
     "legendFormat": " {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "metrics mode: rate of 'forward leaps'",
   "type": "graph",
   "description": "Rate built from counter: number of times a time series was forward-leaped (by N minutes) to not fall behind wall time too much",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "rate(counter_forward_leap{job=\"looker\"}[30s])",
     "legendFormat": " {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "push data rate (on wire vs. log payload)",
   "type": "graph",
   "description": "push rate of serialized & compressed LSFs vs.\npush rate of payload data (log msg size)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps", "label": "data rate" }
   ],
   "targets": [
    {
     "expr": "rate(counter_serialized_fragments_bytes_pushed{job=\"looker\"}[30s])",
     "legendFormat": "on wire, {{looker_invocation_id}}"
    },
    {
     "expr": "rate(counter_payload_bytes_pushed{job=\"looker\"}[30s])",
     "legendFormat": "log payload, {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "metrics mode: rate of 'fragment generation delayed'",
   "type": "graph",
   "description": "Rate built from counter: number of times fragment generation was delayed (in metrics mode) because otherwise we would overtake wall time",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "rate(counter_fragment_generation_delayed{job=\"looker\"}[30s])",
     "legendFormat": " {{looker_invocation_id}}"
    }
   ]
  },
  {
   "title": "push compression factor in % (75%: on-wire data is 25 % of transmitted payload data w/o timestamps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(counter_payload_bytes_pushed{job=\"looker\"}[30s]) - rate(counter_serialized_fragments_bytes_pushed{job=\"looker\"}[30s])) / rate(counter_payload_bytes_pushed{job=\"looker\"}[30s]) * 100",
     "legendFormat": "{{looker_invocation_id}}"
    }
   ]
  }
 ]
}