{
 "title": "Opstrace System",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Write Path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "METRICS - Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate)) * 1e3",
     "legendFormat": "p99 latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate)) * 1e3",
     "legendFormat": "p50 latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate)) * 1e3",
     "legendFormat": "p90 latency"
    }
   ]
  },
  {
   "title": "LOGS - Write QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (prometheus, status) (label_replace(label_replace(rate(loki_request_duration_seconds_count{route=~\"api_prom_push|loki_api_v1_push\"}[5m]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{prometheus}} ({{status}})"
    }
   ]
  },
  {
   "title": "TRACES - Write QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(jaeger_tracer_traces_total[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "METRICS - Write QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (prometheus, status) (label_replace(label_replace(rate(cortex_gcs_request_duration_seconds_count[5m]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{prometheus}} ({{status}})"
    }
   ]
  },
  {
   "title": "LOGS - Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": "p99 {{prometheus}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": "p90 {{prometheus}}"
    },
    {
     "expr": "histogram_quantile(0.0, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": "p50 {{prometheus}}"
    }
   ]
  },
  { "title": "Query Path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "METRICS - Read QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (label_replace(label_replace(rate(cortex_request_duration_seconds_count{job=\"cortex.query-frontend\"}[5m]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "LOGS - Read QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (prometheus, status) (label_replace(label_replace(rate(loki_request_duration_seconds_count{route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m]), \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"), \"status\", \"${1}\",   \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{prometheus}} ({{status}})"
    }
   ]
  },
  {
   "title": "METRICS - Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (prometheus,le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{route!=\"/frontend.Frontend/Process\"})) * 1e3",
     "legendFormat": "p99 {{prometheus}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum by (prometheus,le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{route!=\"/frontend.Frontend/Process\"})) * 1e3",
     "legendFormat": "p90 {{prometheus}} "
    },
    {
     "expr": "histogram_quantile(0.50, sum by (prometheus,le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{route!=\"/frontend.Frontend/Process\"})) * 1e3",
     "legendFormat": "p50 {{prometheus}} "
    }
   ]
  },
  {
   "title": "LOGS - Read Latecy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": "p99 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": "p90 {{route}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": "p50 {{route}}"
    }
   ]
  },
  { "title": "Critical Cluster Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Node CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_cpu_utilisation:rate1m{job=\"node-exporter\"}\n*\n  instance:node_num_cpu:sum{job=\"node-exporter\"}\n/ ignoring (instance) group_left\n  sum without (instance) (instance:node_num_cpu:sum{job=\"node-exporter\"})\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_memory_utilisation:ratio{job=\"node-exporter\"}\n/ ignoring (instance) group_left\n  count without (instance) (instance:node_memory_utilisation:ratio{job=\"node-exporter\"})\n)\n"
    }
   ]
  },
  {
   "title": "Node Disk Space Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without (device) (\n    max without (fstype, mountpoint) (\n      node_filesystem_size_bytes{job=\"node-exporter\", } - node_filesystem_avail_bytes{job=\"node-exporter\", }\n    )\n  ) \n/ ignoring (instance) group_left\n  sum without (instance, device) (\n    max without (fstype, mountpoint) (\n      node_filesystem_size_bytes{job=\"node-exporter\", }\n    )\n  )\n)  \n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"node-exporter\"}",
     "legendFormat": "{{instance}} Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"node-exporter\"}",
     "legendFormat": "{{instance}} Transmit"
    },
    { "expr": "0" }
   ]
  },
  {
   "title": "Nginx ingress controller requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Kafka messages in per second, fetches per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{topic!=\"\"}[1m]))",
     "legendFormat": "Messages In"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{topic!=\"\"}[1m]))",
     "legendFormat": "Fetches"
    }
   ]
  },
  {
   "title": "Cassandra Operations per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(cassandra_table_operation_latency_seconds_count[5m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Alertmanager notifications rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (integration,namespace) (rate(alertmanager_notifications_total[5m])) ",
     "legendFormat": "{{integration}} - {{namespace}}"
    }
   ]
  },
  {
   "title": "Memcached bytes written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(memcached_written_bytes_total[5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}