{
 "title": "Opstrace Overview Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "60s",
 "panels": [
  { "title": "Opstrace Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[METRICS] API proxy, /api/prom/push, POST requests, rate by status code, (5m mean) ALL tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(cortex_api_proxy_request_duration_seconds_count{container=\"cortex-api\",method=\"POST\",route=\"api_v1_push\"}[5m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "[LOGS] API proxy /loki/api/v1/push, POSTs, rate by status code (5m mean) ALL tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_api_proxy_request_duration_seconds_count{container=\"loki-api\",method=\"POST\",route=\"loki_api_v1_push\",status_code=~\"^2.*\"}[5m]))",
     "legendFormat": "Success: {{status_code}}"
    },
    {
     "expr": "sum by (status_code) (rate(loki_api_proxy_request_duration_seconds_count{container=\"loki-api\",method=\"POST\",route=\"loki_api_v1_push\",status_code!~\"^2.*\"}[5m]))",
     "legendFormat": "Error: {{status_code}}"
    }
   ]
  },
  {
   "title": "[METRICS] API proxy, /api/prom/push, POST requests, rate by status code, (5m mean) BY tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,status_code) (rate(cortex_api_proxy_request_duration_seconds_count{container=\"cortex-api\",method=\"POST\",route=\"api_v1_push\"}[5m]))",
     "legendFormat": "{{namespace}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "[LOGS] API proxy /loki/api/v1/push, POSTs, rate by status code (5m mean) BY tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,status_code) (rate(loki_api_proxy_request_duration_seconds_count{container=\"loki-api\",method=\"POST\",route=\"loki_api_v1_push\",status_code=~\"^2.*\"}[5m]))",
     "legendFormat": "{{namespace}}: {{status_code}}"
    },
    {
     "expr": "sum by (namespace,status_code) (rate(loki_api_proxy_request_duration_seconds_count{container=\"loki-api\",method=\"POST\",route=\"loki_api_v1_push\",status_code!~\"^2.*\"}[5m]))",
     "legendFormat": "{{namespace}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "[METRICS] In-Memory/Active Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_ingester_memory_series{job=~\"cortex.ingester\"}\n/ on(namespace) group_left\nmax by (namespace) (cortex_distributor_replication_factor{job=~\"cortex.distributor\"}))\n",
     "legendFormat": "In-memory series"
    },
    {
     "expr": "sum(cortex_ingester_active_series{job=~\"cortex.ingester\"}\n/ on(namespace) group_left\nmax by (namespace) (cortex_distributor_replication_factor{job=~\"cortex.distributor\"}))",
     "legendFormat": "Recently active series"
    }
   ]
  },
  {
   "title": "[LOGS] Rate of log entries vs. bytes per entry; total bytes per second (5m mean) ALL tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "entry rate"
    },
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m]))/sum(rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "bytes per entry"
    },
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m]))",
     "legendFormat": "Total bytes per second"
    }
   ]
  },
  {
   "title": "[METRICS] Ingester inflight push requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cortex_ingester_instance_limits{limit=\"max_inflight_push_requests\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(cortex_inflight_requests{route=\"/cortex.Ingester/Push\",service=\"ingester\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "[LOGS] Ingester inflight push requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loki_inflight_requests{route=\"/logproto.Pusher/Push\",service=\"ingester\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "[METRICS] Ingester Heap Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_heap_objects{namespace=\"cortex\",service=\"ingester\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "[LOGS] Ingester Heap Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_heap_objects{namespace=\"loki\",service=\"ingester\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "[METRICS] Ingester Write Latency [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{job=\"cortex.ingester\"})) * 1e3",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{job=\"cortex.ingester\"})) * 1e3",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{job=\"cortex.ingester\"})) * 1e3",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "[LOGS] Loki request latency (p50, p95, p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"loki.ingester\"})) ",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"loki.ingester\"})) ",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"loki.ingester\"})) ",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "[METRICS] API proxy /api/v1/query[_range], GETs, rate (5m mean) ALL tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status_code) (rate(cortex_api_proxy_request_duration_seconds_count{method=\"GET\", route=~\"api_v1_query.*\"}[5m])) OR on() vector(0)",
     "legendFormat": "{{job}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "[LOGS] API proxy /api/v1/query[_range], GETs, rate (5m mean) ALL tenants",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (job, status_code) (rate(loki_api_proxy_request_duration_seconds_count{method=\"GET\", route=~\"loki_api_v1_query.*|loki_api_v1_tail\"}[5m])) OR on() vector(0)",
     "legendFormat": "{{job}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "[WIP] Compactor error rate?",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_compactor_group_compactions_failures_total[60m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "[WIP] Compactor metrics scratch pad",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_compactor_meta_sync_duration_seconds_bucket[5m])) by (le, pod))",
     "legendFormat": "{{pod}} 95pct meta sync duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cortex_compactor_garbage_collection_duration_seconds_bucket[5m])) by (le, pod))",
     "legendFormat": "{{pod}} 95pct collection duration"
    }
   ]
  },
  {
   "title": "Queries through Grafana, request duration (5m mean) by namespace, status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "duration [s]" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,code) (rate(grafana_datasource_request_duration_seconds_sum{datasource=\"metrics\"}[5m]) / rate(grafana_datasource_request_duration_seconds_count{datasource=\"metrics\"}[5m]))",
     "legendFormat": "{{namespace}}: {{status_code}}"
    }
   ]
  },
  {
   "title": "[METRICS] Ring state seen by service",
   "type": "graph",
   "description": "ACTIVE state uses `min` whereas non-ACTIVE states use `max`; see queries for details.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "number of members in state" }
   ],
   "targets": [
    {
     "expr": "max by (service, state) (cortex_ring_members{namespace=\"cortex\", state!=\"ACTIVE\", name=\"ingester\"}) ",
     "legendFormat": "{{state}} -- {{service}}"
    },
    {
     "expr": "min by (service, state) (cortex_ring_members{namespace=\"cortex\", state=\"ACTIVE\", name=\"ingester\"}) ",
     "legendFormat": "{{state}} -- {{service}}"
    }
   ]
  },
  {
   "title": "[LOGS] Ring state seen by service",
   "type": "graph",
   "description": "ACTIVE state uses `min` whereas non-ACTIVE states use `max`; see queries for details.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short", "label": "number of members in state" }
   ],
   "targets": [
    {
     "expr": "max by (service, state) (cortex_ring_members{namespace=\"loki\", state!=\"ACTIVE\", name=\"ingester\"}) ",
     "legendFormat": "{{state}} -- {{service}}"
    },
    {
     "expr": "min by (service, state) (cortex_ring_members{namespace=\"loki\", state=\"ACTIVE\", name=\"ingester\"}) ",
     "legendFormat": "{{state}} -- {{service}}"
    }
   ]
  },
  {
   "title": "[METRICS] Object Storage - RPS / WPS [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(thanos_objstore_bucket_operations_total[1m])) by (operation)"
    }
   ]
  },
  {
   "title": "[LOGS] Object Storage - RPS / WPS [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cortex_s3_request_duration_seconds_count[1m])) by (operation)"
    }
   ]
  },
  {
   "title": "Opstrace Cluster Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 }
  },
  {
   "title": "Instance CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_cpu_utilisation:rate1m{job=\"node-exporter\"}\n*\n  instance:node_num_cpu:sum{job=\"node-exporter\"}\n/ ignoring (instance) group_left\n  sum without (instance) (instance:node_num_cpu:sum{job=\"node-exporter\"})\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Instance Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  instance:node_memory_utilisation:ratio{job=\"node-exporter\"}\n/ ignoring (instance) group_left\n  count without (instance) (instance:node_memory_utilisation:ratio{job=\"node-exporter\"})\n)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Linux Load Average (average of instances, min & max)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(node_load15)", "legendFormat": "load15_avg" },
    { "expr": "min(node_load15)", "legendFormat": "min" },
    { "expr": "max(node_load15)", "legendFormat": "max" }
   ]
  },
  {
   "title": "Memory Swap (should always be 0)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "avg(container_memory_swap)", "legendFormat": "container_swap_avg" },
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "node_swap_{{instance}}" }
   ]
  },
  {
   "title": "Container CPU (by namespace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Container Mem (by namespace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Container CPU (by Pod)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Mem (by Pod)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling by pod (seconds) [5m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "[WIP] Memory - OOMKills",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"} > 0"
    }
   ]
  },
  {
   "title": "Pod States (log)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "RUNNING"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated)",
     "legendFormat": "TERMINATED"
    },
    {
     "expr": "sum(kube_pod_container_status_ready)",
     "legendFormat": "READY"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "WAITING"
    }
   ]
  },
  {
   "title": "Pod Restart Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container, namespace) (rate(kube_pod_container_status_restarts_total{namespace!=\"kube-system\"}[5m]))",
     "legendFormat": "{{container}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "[METRICS] PVC Storage Used Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", namespace=\"cortex\"})\n  -\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", namespace=\"cortex\"})\n)\n/\nsum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", namespace=\"cortex\"})\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "[LOGS] PVC Storage Used Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", namespace=\"loki\"})\n  -\n  sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", namespace=\"loki\"})\n)\n/\nsum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", namespace=\"loki\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Instance Network Tx/Rx [1m] (stacked)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate1m{job=\"node-exporter\"}",
     "legendFormat": "{{instance}} Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate1m{job=\"node-exporter\"}",
     "legendFormat": "{{instance}} Transmit"
    }
   ]
  },
  {
   "title": "Instance Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}