{
 "title": "Quick Start Overview",
 "description": "Key metrics demonstrating incoming data.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "[METRICS] API requests rate by status code (myteam tenant ONLY)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(cortex_api_proxy_request_duration_seconds_count{job=\"myteam-tenant.cortex-api\",method=\"POST\",route=\"api_v1_push\"}[5m])) OR on() vector(0)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "[LOGS] API request rate by status code (myteam tenant ONLY)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_api_proxy_request_duration_seconds_count{job=\"myteam-tenant.loki-api\",method=\"POST\",route=\"loki_api_v1_push\",status_code=~\"^2.*\"}[5m])) OR on() vector(0)",
     "legendFormat": "Success: {{status_code}}"
    },
    {
     "expr": "sum by (status_code) (rate(loki_api_proxy_request_duration_seconds_count{job=\"myteam-tenant.loki-api\",method=\"POST\",route=\"loki_api_v1_push\",status_code!~\"^2.*\"}[5m])) OR on() vector(0)",
     "legendFormat": "Error: {{status_code}}"
    }
   ]
  },
  {
   "title": "[METRICS] Total Number of Active Series (total across system AND myteam tenants)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_ingester_memory_series{job=~\"cortex.ingester\"}\n/ on(namespace) group_left\nmax by (namespace) (cortex_distributor_replication_factor{job=~\"cortex.distributor\"}))\n"
    }
   ]
  },
  {
   "title": "[LOGS] Total Number of Log Lines Received (total across system AND myteam tenants)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(loki_distributor_lines_received_total)",
     "legendFormat": "log entry rate"
    }
   ]
  },
  {
   "title": "[METRICS] Ingestion (Write) Latency (all tenants)",
   "type": "graph",
   "description": "\"sum(rate(cortex_request_duration_seconds_bucket[1m])) by (le, job, route)\",",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{job=\"cortex.ingester\"})) * 1e3",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{job=\"cortex.ingester\"})) * 1e3",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (job_route:cortex_request_duration_seconds_bucket:sum_rate{job=\"cortex.ingester\"})) * 1e3",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "[LOGS]  Ingestion (Write) Latency (p50, p95, p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"loki.ingester\"})) ",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"loki.ingester\"})) ",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"loki.ingester\"})) ",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}