{
 "title": "Tenant Overview / Cortex",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*cortex.*\"}, namespace)"
    }
   },
   { "name": "timewindow", "label": "Time window width", "query": "1m, 2m, 3m, 4m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "API proxy /api/v1/push, POSTs, rate by status code ($timewindow mean, tenant: '$tenant')",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(cortex_api_proxy_request_duration_seconds_count{job=\"$tenant-tenant.cortex-api\",method=\"POST\",route=\"api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Number of active time series (tenant: '$tenant')",
   "type": "stat",
   "description": "Summed over all ingesters and divided by the replication factor. Based on the 'active series' definition, using an idle period of 10 minutes.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_active_series{user=\"$tenant\"}) / max(cortex_distributor_replication_factor{namespace=\"cortex\", job=\"cortex.distributor\"})"
    }
   ]
  },
  {
   "title": "distributor: sample recv rate ($timewindow mean,  tenant: '$tenant')",
   "type": "graph",
   "description": "before rejection, validation?",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "receive rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_distributor_received_samples_total{user=\"$tenant\"}[$timewindow]))",
     "legendFormat": "recv sample rate"
    }
   ]
  },
  {
   "title": "ingesters: number of active series in memory (tenant: '$tenant')",
   "type": "graph",
   "description": "Updated once per minute.\nActive series idle timeout: 10 minutes.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_active_series{user=\"$tenant\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API proxy /api/v1/push, 2xx-acked POSTs, request duration, event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (le) (rate(cortex_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.cortex-api\",method=\"POST\",status_code=~\"200|202\",route=\"api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ingesters: TSDB head chunk creation rate  ($timewindow mean, tenant: '$tenant')",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cortex_ingester_tsdb_head_chunks_created_total{user=\"$tenant\"}[$timewindow])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries through Grafana, req duration by status code ($timewindow mean, tenant: '$tenant')",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "duration [s]" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(grafana_datasource_request_duration_seconds_sum{namespace=\"$tenant-tenant\", datasource=\"metrics\"}[$timewindow]) / rate(grafana_datasource_request_duration_seconds_count{namespace=\"$tenant-tenant\", datasource=\"metrics\"}[$timewindow]))\n"
    }
   ]
  },
  {
   "title": "compactor: total number of blocks in storage bucket (tenant: '$tenant')",
   "type": "graph",
   "description": "Includes blocks marked for deletion, but not partial blocks",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cortex_bucket_blocks_count{namespace=\"cortex\", user=\"$tenant\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API proxy /api/v1/query[_range], GETs, rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(cortex_api_proxy_request_duration_seconds_count{job=\"$tenant-tenant.cortex-api\",method=\"GET\",route=~\"api_v1_query.*\"}[$timewindow]))"
    }
   ]
  },
  {
   "title": "ingesters: TSDB local storage used (tenant: '$tenant')",
   "type": "graph",
   "description": "The number of bytes that are currently used for local storage by all blocks, for the given user/tenant.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_tsdb_storage_blocks_bytes{user=\"$tenant\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API proxy /api/v1/query[_range], 200-acked GETs, request duration, event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (le) (rate(cortex_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.cortex-api\",method=\"GET\",status_code=\"200\",route=~\"api_v1_query.*\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}