{
 "title": "Tenant Overview / Loki",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*cortex.*\"}, namespace)"
    }
   },
   { "name": "timewindow", "label": "Time window width", "query": "1m, 2m, 3m, 4m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "API proxy /loki/api/v1/push, POSTs, rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(loki_api_proxy_request_duration_seconds_count{job=\"$tenant-tenant.loki-api\",method=\"POST\",route=\"loki_api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "distributor: tenant: $tenant, ingest rate before rejection ($timewindow mean, tenant: '$tenant')",
   "type": "graph",
   "description": "the counter is increased while reading the request body, before validation, and before passing things on to the ingester.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "receive rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{tenant=\"$tenant\"}[$timewindow]))",
     "legendFormat": "log entry rate"
    },
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{tenant=\"$tenant\"}[$timewindow]))",
     "legendFormat": "byte rate"
    }
   ]
  },
  {
   "title": "API proxy /loki/api/v1/push, 2xx-acked POSTs, request duration, event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le) (rate(loki_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.loki-api\",method=\"POST\",status_code=\"204\",route=\"loki_api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ingesters: total bytes stored in chunks (tenant: '$tenant')",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "loki_ingester_chunk_stored_bytes_total{tenant=\"$tenant\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries through Grafana, req duration by status code ($timewindow mean, tenant: '$tenant')",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "duration [s]" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(grafana_datasource_request_duration_seconds_sum{namespace=\"$tenant-tenant\", datasource=\"logs\"}[$timewindow]) / rate(grafana_datasource_request_duration_seconds_count{namespace=\"$tenant-tenant\", datasource=\"logs\"}[$timewindow]))\n"
    }
   ]
  },
  {
   "title": "ingesters: currently active number of streams (tenant: '$tenant')",
   "type": "graph",
   "description": "loki_ingester_streams_created_total - loki_ingester_streams_removed_total",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "loki_ingester_streams_created_total{tenant=\"$tenant\"}-loki_ingester_streams_removed_total{tenant=\"$tenant\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API proxy, /loki/api/v1/query[_range], 200-acked GETs, total request processing duration, event rate [1/s]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (rate(loki_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.loki-api\",method=\"GET\",status_code=\"200\",route=~\"loki_api_v1_query_.*\"}[$timewindow]))"
    }
   ]
  },
  {
   "title": "ingesters: stream creation rate ($timewindow mean, tenant: '$tenant')",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total{tenant=\"$tenant\"}[$timewindow])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}