FROM golang:1.16 AS build-env
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GOPATH=/go

# Prepare and enter src directory
WORKDIR /go/src/github.com/opstrace/opstrace/go/

# Cache dependencies
ADD go.mod .
ADD go.sum .
RUN go mod download -x

# Add the sources and proceed with build
ADD . .
RUN make build-config

FROM scratch
COPY --from=build-env /go/src/github.com/opstrace/opstrace/go/config-api /
ENTRYPOINT ["/config-api"]
