/**
 * Copyright 2021 Opstrace, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable */
import localVarRequest from "request";
import { Request } from "request";
import {
  createReducer,
  createAsyncAction,
  ActionType,
  createAction
} from "typesafe-actions";
import {
  ApiKeyAuth,
  Authentication,
  ObjectSerializer,
  K8sResource,
  isSameObject,
  ResourceCache,
  VoidAuth } from "../common";
import { IncomingMessage } from "http";
import {
  V1Status,
  V1ListMeta,
  KubeConfig,
  Watch,
  Interceptor
} from "@kubernetes/client-node";
import { log } from "@opstrace/utils";

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * allows customize `clickhouse-operator` settings, need restart clickhouse-operator pod after adding, more details https://github.com/Altinity/clickhouse-operator/blob/master/docs/operator_configuration.md
 */
export interface V1Clickhouseoperatorconfiguration {
  status?: {
    [k: string]: any;
  };
  /**
   * allows define some of settings for `clickhouse-operator` itself,
   * More info: https://github.com/Altinity/clickhouse-operator/blob/master/config/config.yaml
   * look to etc-clickhouse-operator* ConfigMaps if you need more control
   *
   */
  spec?: {
    /**
     * List of namespaces where clickhouse-operator watches for events.
     */
    watchNamespaces?: string[];
    /**
     * Path to folder where ClickHouse configuration files common for all instances within CHI are located. Default - config.d
     */
    chCommonConfigsPath?: string;
    /**
     * Path to folder where ClickHouse configuration files unique for each instance (host) within CHI are located. Default - conf.d
     */
    chHostConfigsPath?: string;
    /**
     * Path to folder where ClickHouse configuration files with users settings are located. Files are common for all instances within CHI
     */
    chUsersConfigsPath?: string;
    /**
     * Path to folder where ClickHouseInstallation .yaml manifests are located.
     */
    chiTemplatesPath?: string;
    /**
     * How many seconds to wait for created/updated StatefulSet to be Ready
     */
    statefulSetUpdateTimeout?: number;
    /**
     * How many seconds to wait between checks for created/updated StatefulSet status
     */
    statefulSetUpdatePollPeriod?: number;
    /**
     * What to do in case created StatefulSet is not in Ready after `statefulSetUpdateTimeout` seconds
     * Possible options:
     * 1. abort - do nothing, just break the process and wait for admin.
     * 2. delete - delete newly created problematic StatefulSet.
     * 3. ignore (default) - ignore error, pretend nothing happened and move on to the next StatefulSet.
     *
     */
    onStatefulSetCreateFailureAction?: string;
    /**
     * What to do in case updated StatefulSet is not in Ready after `statefulSetUpdateTimeout` seconds
     * Possible options:
     * 1. abort - do nothing, just break the process and wait for admin.
     * 2. rollback (default) - delete Pod and rollback StatefulSet to previous Generation. Pod would be recreated by StatefulSet based on rollback-ed configuration.
     * 3. ignore - ignore error, pretend nothing happened and move on to the next StatefulSet.
     *
     */
    onStatefulSetUpdateFailureAction?: string;
    /**
     * ClickHouse server configuration `<profile>...</profile>` for any <user>
     */
    chConfigUserDefaultProfile?: string;
    /**
     * ClickHouse server configuration `<quota>...</quota>` for any <user>
     */
    chConfigUserDefaultQuota?: string;
    /**
     * ClickHouse server configuration `<networks><ip>...</ip></netrworks>` for any <user>
     */
    chConfigUserDefaultNetworksIP?: string[];
    /**
     * ClickHouse server configuration `<password>...</password>` for any <user>
     */
    chConfigUserDefaultPassword?: string;
    /**
     * ClickHouse server configuration `<host_regexp>...</host_regexp>` for any <user>
     */
    chConfigNetworksHostRegexpTemplate?: string;
    /**
     * ClickHouse username to be used by operator to connect to ClickHouse instances, deprecated, use chCredentialsSecretName
     */
    chUsername?: string;
    /**
     * ClickHouse password to be used by operator to connect to ClickHouse instances, deprecated, use chCredentialsSecretName
     */
    chPassword?: string;
    /**
     * Location of k8s Secret with username and password to be used by operator to connect to ClickHouse instances
     */
    chCredentialsSecretNamespace?: string;
    /**
     * Name of k8s Secret with username and password to be used by operator to connect to ClickHouse instances
     */
    chCredentialsSecretName?: string;
    /**
     * Name of k8s Secret with username and password to be used by operator to connect to ClickHouse instances
     */
    chPort?: number;
    /**
     * boolean, allows logs to stderr
     */
    logtostderr?: string;
    /**
     * booleanm allows logs to stderr and files both
     */
    alsologtostderr?: string;
    /**
     * verbosity level of clickhouse-operator log, default - 1 max - 9
     */
    v?: string;
    stderrthreshold?: string;
    vmodule?: string;
    log_backtrace_at?: string;
    /**
     * how much goroutines will use to reconcile in parallel, 10 by default
     */
    reconcileThreadsNumber?: number;
    reconcileWaitExclude?: string;
    reconcileWaitInclude?: string;
    /**
     * When propagating labels from the chi's `metadata.labels` section to child objects' `metadata.labels`,
     * exclude labels from the following list
     *
     */
    excludeFromPropagationLabels?: string[];
    /**
     * Whether to append *Scope* labels to StatefulSet and Pod
     */
    appendScopeLabels?:
      | ""
      | "0"
      | "1"
      | "False"
      | "false"
      | "True"
      | "true"
      | "No"
      | "no"
      | "Yes"
      | "yes"
      | "Off"
      | "off"
      | "On"
      | "on"
      | "Disable"
      | "disable"
      | "Enable"
      | "enable"
      | "Disabled"
      | "disabled"
      | "Enabled"
      | "enabled"
      | "LabelShardScopeIndex"
      | "LabelReplicaScopeIndex"
      | "LabelCHIScopeIndex"
      | "LabelCHIScopeCycleSize"
      | "LabelCHIScopeCycleIndex"
      | "LabelCHIScopeCycleOffset"
      | "LabelClusterScopeIndex"
      | "LabelClusterScopeCycleSize"
      | "LabelClusterScopeCycleIndex"
      | "LabelClusterScopeCycleOffset";
    [k: string]: any;
  };
  [k: string]: any;
}

export interface V1ClickhouseoperatorconfigurationList {
  /**
    * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
    */
   apiVersion?: string;
   /**
   * Items is the list of ControllerRevisions
   */
   items: Array<V1Clickhouseoperatorconfiguration>;
   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   */
   kind?: string;
   metadata?: V1ListMeta;
}

let defaultBasePath = 'http://localhost';

export enum V1ClickhouseoperatorconfigurationApiApiKeys {
    BearerToken,
}

export class V1ClickhouseoperatorconfigurationApi {
  protected _basePath = defaultBasePath;
  protected _defaultHeaders : any = {};
  protected _useQuerystring : boolean = false;

  protected authentications = {
      'default': <Authentication>new VoidAuth(),
      'BearerToken': new ApiKeyAuth('header', 'authorization'),
  }

  protected interceptors: Interceptor[] = [];

  constructor(basePath?: string);
  constructor(basePathOrUsername: string, password?: string, basePath?: string) {
      if (password) {
          if (basePath) {
              this.basePath = basePath;
          }
      } else {
          if (basePathOrUsername) {
              this.basePath = basePathOrUsername
          }
      }
  }

  set useQuerystring(value: boolean) {
      this._useQuerystring = value;
  }

  set basePath(basePath: string) {
      this._basePath = basePath;
  }

  set defaultHeaders(defaultHeaders: any) {
      this._defaultHeaders = defaultHeaders;
  }

  get defaultHeaders() {
      return this._defaultHeaders;
  }

  get basePath() {
      return this._basePath;
  }

  public setDefaultAuthentication(auth: Authentication) {
      this.authentications.default = auth;
  }

  public setApiKey(key: V1ClickhouseoperatorconfigurationApiApiKeys, value: string) {
    (this.authentications as any)[V1ClickhouseoperatorconfigurationApiApiKeys[key]].apiKey = value;
  }

  public addInterceptor(interceptor: Interceptor) {
      this.interceptors.push(interceptor);
  }

  /**
   * create a V1Clickhouseoperatorconfiguration
   * @param namespace object name and auth scope, such as for teams and projects
   * @param body
   * @param includeUninitialized If true, partially initialized resources are included in the response.
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   */
  public async createNamespacedV1Clickhouseoperatorconfiguration (namespace: string, body: V1Clickhouseoperatorconfiguration, includeUninitialized?: boolean, pretty?: string, dryRun?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: IncomingMessage; body: V1Clickhouseoperatorconfiguration;  }> {
    const localVarPath = this.basePath + '/apis/clickhouse.altinity.com/v1/namespaces/{namespace}/clickhouseoperatorconfigurations'
        .replace('{' + 'namespace' + '}', encodeURIComponent(String(namespace)));
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
    let localVarFormParams: any = {};

    // verify required parameter 'namespace' is not null or undefined
    if (namespace === null || namespace === undefined) {
        throw new Error('Required parameter namespace was null or undefined when calling createNamespacedV1Clickhouseoperatorconfiguration.');
    }

    // verify required parameter 'body' is not null or undefined
    if (body === null || body === undefined) {
        throw new Error('Required parameter body was null or undefined when calling createNamespacedV1Clickhouseoperatorconfiguration.');
    }

    if (includeUninitialized !== undefined) {
        localVarQueryParameters['includeUninitialized'] = includeUninitialized;
    }

    if (pretty !== undefined) {
        localVarQueryParameters['pretty'] = pretty;
    }

    if (dryRun !== undefined) {
        localVarQueryParameters['dryRun'] = dryRun;
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
        method: 'POST',
        qs: localVarQueryParameters,
        headers: localVarHeaderParams,
        uri: localVarPath,
        useQuerystring: this._useQuerystring,
        json: true,
        body: body
    };

    let authenticationPromise = Promise.resolve();
    authenticationPromise = authenticationPromise.then(() => this.authentications.BearerToken.applyToRequest(localVarRequestOptions));

    authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
    return authenticationPromise.then(() => {
        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: IncomingMessage; body: V1Clickhouseoperatorconfiguration;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    });
  }

  /**
   * read the specified V1Clickhouseoperatorconfiguration
   * @param name name of the V1Clickhouseoperatorconfiguration
   * @param namespace object name and auth scope, such as for teams and projects
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param exact Should the export be exact.  Exact export maintains cluster-specific fields like &#39;Namespace&#39;.
   * @param _export Should this value be exported.  Export strips fields that a user can not specify.
   */
  public async readNamespacedV1Clickhouseoperatorconfiguration (name: string, namespace: string, pretty?: string, exact?: boolean, _export?: boolean, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: IncomingMessage; body: V1Clickhouseoperatorconfiguration;  }> {
    const localVarPath = this.basePath + '/apis/clickhouse.altinity.com/v1/namespaces/{namespace}/clickhouseoperatorconfigurations/{name}'
      .replace('{' + 'name' + '}', encodeURIComponent(String(name)))
      .replace('{' + 'namespace' + '}', encodeURIComponent(String(namespace)));
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
    let localVarFormParams: any = {};

    // verify required parameter 'name' is not null or undefined
    if (name === null || name === undefined) {
        throw new Error('Required parameter name was null or undefined when calling readNamespacedV1Clickhouseoperatorconfiguration.');
    }

    // verify required parameter 'namespace' is not null or undefined
    if (namespace === null || namespace === undefined) {
        throw new Error('Required parameter namespace was null or undefined when calling readNamespacedV1Clickhouseoperatorconfiguration.');
    }

    if (pretty !== undefined) {
      localVarQueryParameters['pretty'] = pretty;
    }

    if (exact !== undefined) {
        localVarQueryParameters['exact'] = exact;
    }

    if (_export !== undefined) {
        localVarQueryParameters['export'] = _export;
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
        method: 'GET',
        qs: localVarQueryParameters,
        headers: localVarHeaderParams,
        uri: localVarPath,
        useQuerystring: this._useQuerystring,
        json: true,
    };

    let authenticationPromise = Promise.resolve();
    authenticationPromise = authenticationPromise.then(() => this.authentications.BearerToken.applyToRequest(localVarRequestOptions));

    authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
    return authenticationPromise.then(() => {
        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: IncomingMessage; body: V1Clickhouseoperatorconfiguration;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    });
  }

  /**
   * partially update the specified V1Clickhouseoperatorconfiguration
   * @param name name of the V1Clickhouseoperatorconfiguration
   * @param namespace object name and auth scope, such as for teams and projects
   * @param body
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   */
  public async patchNamespacedV1Clickhouseoperatorconfiguration (name: string, namespace: string, body: object, pretty?: string, dryRun?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: IncomingMessage; body: V1Clickhouseoperatorconfiguration;  }> {
    const localVarPath = this.basePath + '/apis/clickhouse.altinity.com/v1/namespaces/{namespace}/clickhouseoperatorconfigurations/{name}'
        .replace('{' + 'name' + '}', encodeURIComponent(String(name)))
        .replace('{' + 'namespace' + '}', encodeURIComponent(String(namespace)));
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
    let localVarFormParams: any = {};

    // verify required parameter 'name' is not null or undefined
    if (name === null || name === undefined) {
        throw new Error('Required parameter name was null or undefined when calling patchNamespacedV1Clickhouseoperatorconfiguration.');
    }

    // verify required parameter 'namespace' is not null or undefined
    if (namespace === null || namespace === undefined) {
        throw new Error('Required parameter namespace was null or undefined when calling patchNamespacedV1Clickhouseoperatorconfiguration.');
    }

    // verify required parameter 'body' is not null or undefined
    if (body === null || body === undefined) {
        throw new Error('Required parameter body was null or undefined when calling patchNamespacedV1Clickhouseoperatorconfiguration.');
    }

    if (pretty !== undefined) {
        localVarQueryParameters['pretty'] = pretty;
    }

    if (dryRun !== undefined) {
        localVarQueryParameters['dryRun'] = dryRun;
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
        method: 'PATCH',
        qs: localVarQueryParameters,
        headers: localVarHeaderParams,
        uri: localVarPath,
        useQuerystring: this._useQuerystring,
        json: true,
        body: body
    };

    let authenticationPromise = Promise.resolve();
    authenticationPromise = authenticationPromise.then(() => this.authentications.BearerToken.applyToRequest(localVarRequestOptions));

    authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
    return authenticationPromise.then(() => {
        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: IncomingMessage; body: V1Clickhouseoperatorconfiguration;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    });
  }

  /**
   * delete a V1Clickhouseoperatorconfiguration
   * @param name name of the V1Clickhouseoperatorconfiguration
   * @param namespace object name and auth scope, such as for teams and projects
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param dryRun When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
   * @param gracePeriodSeconds The duration in seconds before the object should be deleted. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period for the specified type will be used. Defaults to a per object value if not specified. zero means delete immediately.
   * @param orphanDependents Deprecated: please use the PropagationPolicy, this field will be deprecated in 1.7. Should the dependent objects be orphaned. If true/false, the &quot;orphan&quot; finalizer will be added to/removed from the object&#39;s finalizers list. Either this field or PropagationPolicy may be set, but not both.
   * @param propagationPolicy Whether and how garbage collection will be performed. Either this field or OrphanDependents may be set, but not both. The default policy is decided by the existing finalizer set in the metadata.finalizers and the resource-specific default policy. Acceptable values are: &#39;Orphan&#39; - orphan the dependents; &#39;Background&#39; - allow the garbage collector to delete the dependents in the background; &#39;Foreground&#39; - a cascading policy that deletes all dependents in the foreground.
   * @param body
   */
  public async deleteNamespacedV1Clickhouseoperatorconfiguration (name: string, namespace: string, pretty?: string, dryRun?: string, gracePeriodSeconds?: number, orphanDependents?: boolean, propagationPolicy?: string, body?: any, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: IncomingMessage; body: V1Status;  }> {
    const localVarPath = this.basePath + '/apis/clickhouse.altinity.com/v1/namespaces/{namespace}/clickhouseoperatorconfigurations/{name}'
        .replace('{' + 'name' + '}', encodeURIComponent(String(name)))
        .replace('{' + 'namespace' + '}', encodeURIComponent(String(namespace)));
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
    let localVarFormParams: any = {};

    // verify required parameter 'name' is not null or undefined
    if (name === null || name === undefined) {
        throw new Error('Required parameter name was null or undefined when calling deleteNamespacedV1Clickhouseoperatorconfiguration.');
    }

    // verify required parameter 'namespace' is not null or undefined
    if (namespace === null || namespace === undefined) {
        throw new Error('Required parameter namespace was null or undefined when calling deleteNamespacedV1Clickhouseoperatorconfiguration.');
    }

    if (pretty !== undefined) {
        localVarQueryParameters['pretty'] = pretty;
    }

    if (dryRun !== undefined) {
        localVarQueryParameters['dryRun'] = dryRun;
    }

    if (gracePeriodSeconds !== undefined) {
        localVarQueryParameters['gracePeriodSeconds'] = gracePeriodSeconds;
    }

    if (orphanDependents !== undefined) {
        localVarQueryParameters['orphanDependents'] = orphanDependents;
    }

    if (propagationPolicy !== undefined) {
        localVarQueryParameters['propagationPolicy'] = propagationPolicy;
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
        method: 'DELETE',
        qs: localVarQueryParameters,
        headers: localVarHeaderParams,
        uri: localVarPath,
        useQuerystring: this._useQuerystring,
        json: true,
        body: {}
    };

    let authenticationPromise = Promise.resolve();
    authenticationPromise = authenticationPromise.then(() => this.authentications.BearerToken.applyToRequest(localVarRequestOptions));

    authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
    return authenticationPromise.then(() => {
        if (Object.keys(localVarFormParams).length) {
            if (localVarUseFormData) {
                (<any>localVarRequestOptions).formData = localVarFormParams;
            } else {
                localVarRequestOptions.form = localVarFormParams;
            }
        }
        return new Promise<{ response: IncomingMessage; body: V1Status;  }>((resolve, reject) => {
            localVarRequest(localVarRequestOptions, (error, response, body) => {
                if (error) {
                    reject(error);
                } else {
                    body = ObjectSerializer.deserialize(body, "V1Status");
                    if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                        resolve({ response: response, body: body });
                    } else {
                        reject({ response: response, body: body });
                    }
                }
            });
        });
    });
  }

  /**
   * list or watch objects of kind V1Clickhouseoperatorconfiguration
   * @param allowWatchBookmarks allowWatchBookmarks requests watch events with type &quot;BOOKMARK&quot;. Servers that do not implement bookmarks may ignore this flag and bookmarks are sent at the server&#39;s discretion. Clients should not assume bookmarks are returned at any specific interval, nor may they assume the server will send any BOOKMARK event during a session. If this is not a watch, this field is ignored. If the feature gate WatchBookmarks is not enabled in apiserver, this field is ignored.  This field is alpha and can be changed or removed without notice.
   * @param _continue The continue option should be set when retrieving more results from the server. Since this value is server defined, clients may only use the continue value from a previous query result with identical query parameters (except for the value of continue) and the server may reject a continue value it does not recognize. If the specified continue value is no longer valid whether due to expiration (generally five to fifteen minutes) or a configuration change on the server, the server will respond with a 410 ResourceExpired error together with a continue token. If the client needs a consistent list, it must restart their list without the continue field. Otherwise, the client may send another list request with the token received with the 410 error, the server will respond with a list starting from the next key, but from the latest snapshot, which is inconsistent from the previous list results - objects that are created, modified, or deleted after the first list request will be included in the response, as long as their keys are after the &quot;next key&quot;.  This field is not supported when watch is true. Clients may start a watch from the last resourceVersion value returned by the server and not miss any modifications.
   * @param fieldSelector A selector to restrict the list of returned objects by their fields. Defaults to everything.
   * @param labelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
   * @param limit limit is a maximum number of responses to return for a list call. If more items exist, the server will set the &#x60;continue&#x60; field on the list metadata to a value that can be used with the same initial query to retrieve the next set of results. Setting a limit may return fewer than the requested amount of items (up to zero items) in the event all requested objects are filtered out and clients should only use the presence of the continue field to determine whether more results are available. Servers may choose not to support the limit argument and will return all of the available results. If limit is specified and the continue field is empty, clients may assume that no more results are available. This field is not supported if watch is true.  The server guarantees that the objects returned when using continue will be identical to issuing a single list call without a limit - that is, no objects created, modified, or deleted after the first request is issued will be included in any subsequent continued requests. This is sometimes referred to as a consistent snapshot, and ensures that a client that is using limit to receive smaller chunks of a very large result can ensure they see all possible objects. If objects are updated during a chunked list the version of the object that was present at the time the first list result was calculated is returned.
   * @param pretty If &#39;true&#39;, then the output is pretty printed.
   * @param resourceVersion When specified with a watch call, shows changes that occur after that particular version of a resource. Defaults to changes from the beginning of history. When specified for list: - if unset, then the result is returned from remote storage based on quorum-read flag; - if it&#39;s 0, then we simply return what we currently have in cache, no guarantee; - if set to non zero, then the result is at least as fresh as given rv.
   * @param timeoutSeconds Timeout for the list/watch call. This limits the duration of the call, regardless of any activity or inactivity.
   * @param watch Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.
   */
  public async listV1ClickhouseoperatorconfigurationForAllNamespaces (allowWatchBookmarks?: boolean, _continue?: string, fieldSelector?: string, labelSelector?: string, limit?: number, pretty?: string, resourceVersion?: string, timeoutSeconds?: number, watch?: boolean, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: IncomingMessage; body: V1ClickhouseoperatorconfigurationList;  }> {
      const localVarPath = this.basePath + '/apis/clickhouse.altinity.com/v1/clickhouseoperatorconfigurations';
      let localVarQueryParameters: any = {};
      let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);
      let localVarFormParams: any = {};

      if (allowWatchBookmarks !== undefined) {
          localVarQueryParameters['allowWatchBookmarks'] = allowWatchBookmarks;
      }

      if (_continue !== undefined) {
          localVarQueryParameters['continue'] = _continue;
      }

      if (fieldSelector !== undefined) {
          localVarQueryParameters['fieldSelector'] = fieldSelector;
      }

      if (labelSelector !== undefined) {
          localVarQueryParameters['labelSelector'] = labelSelector;
      }

      if (limit !== undefined) {
          localVarQueryParameters['limit'] = limit;
      }

      if (pretty !== undefined) {
          localVarQueryParameters['pretty'] = pretty;
      }

      if (resourceVersion !== undefined) {
          localVarQueryParameters['resourceVersion'] = resourceVersion;
      }

      if (timeoutSeconds !== undefined) {
          localVarQueryParameters['timeoutSeconds'] = timeoutSeconds;
      }

      if (watch !== undefined) {
          localVarQueryParameters['watch'] = watch;
      }

      (<any>Object).assign(localVarHeaderParams, options.headers);

      let localVarUseFormData = false;

      let localVarRequestOptions: localVarRequest.Options = {
          method: 'GET',
          qs: localVarQueryParameters,
          headers: localVarHeaderParams,
          uri: localVarPath,
          useQuerystring: this._useQuerystring,
          json: true,
      };

      let authenticationPromise = Promise.resolve();
      authenticationPromise = authenticationPromise.then(() => this.authentications.BearerToken.applyToRequest(localVarRequestOptions));

      authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
      return authenticationPromise.then(() => {
          if (Object.keys(localVarFormParams).length) {
              if (localVarUseFormData) {
                  (<any>localVarRequestOptions).formData = localVarFormParams;
              } else {
                  localVarRequestOptions.form = localVarFormParams;
              }
          }
          return new Promise<{ response: IncomingMessage; body: V1ClickhouseoperatorconfigurationList;  }>((resolve, reject) => {
              localVarRequest(localVarRequestOptions, (error, response, body) => {
                  if (error) {
                      reject(error);
                  } else {
                      if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                          resolve({ response: response, body: body });
                      } else {
                          reject({ response: response, body: body });
                      }
                  }
              });
          });
      });
  }};

export type V1ClickhouseoperatorconfigurationResourceType = V1ClickhouseoperatorconfigurationResource;
export type V1ClickhouseoperatorconfigurationResources = V1ClickhouseoperatorconfigurationResourceType[];

export const isV1ClickhouseoperatorconfigurationResource = <(r: K8sResource) => r is V1ClickhouseoperatorconfigurationResourceType>(
  (resource => resource instanceof V1ClickhouseoperatorconfigurationResource)
);

export const V1ClickhouseoperatorconfigurationActions = {
  fetch: createAsyncAction(
    "FETCH_K8S_V1CLICKHOUSEOPERATORCONFIGURATIONS_REQUEST",
    "FETCH_K8S_V1CLICKHOUSEOPERATORCONFIGURATIONS_SUCCESS",
    "FETCH_K8S_V1CLICKHOUSEOPERATORCONFIGURATIONS_FAILURE"
  )<{}, { resources: V1ClickhouseoperatorconfigurationResources }, { error: Error }>(),
  onUpdated: createAction("ON_UPDATED_K8S_V1CLICKHOUSEOPERATORCONFIGURATION")<V1ClickhouseoperatorconfigurationResourceType>(),
  onAdded: createAction("ON_ADDED_K8S_V1CLICKHOUSEOPERATORCONFIGURATION")<V1ClickhouseoperatorconfigurationResourceType>(),
  onDestroyed: createAction("ON_DESTROYED_K8S_V1CLICKHOUSEOPERATORCONFIGURATION")<V1ClickhouseoperatorconfigurationResourceType>()
};
export type V1ClickhouseoperatorconfigurationResourceActions = ActionType<typeof V1ClickhouseoperatorconfigurationActions>;
export interface V1ClickhouseoperatorconfigurationResourceState extends ResourceCache<V1ClickhouseoperatorconfigurationResourceType> {}

const initialState: V1ClickhouseoperatorconfigurationResourceState = {
  loaded: false,
  error: null,
  resources: []
};

export const V1ClickhouseoperatorconfigurationReducer = createReducer<
  V1ClickhouseoperatorconfigurationResourceState,
  V1ClickhouseoperatorconfigurationResourceActions
>(initialState)
  .handleAction(
    V1ClickhouseoperatorconfigurationActions.fetch.request,
    (state, _): V1ClickhouseoperatorconfigurationResourceState => ({
      ...state,
      loaded: false
    })
  )
  .handleAction(
    V1ClickhouseoperatorconfigurationActions.fetch.success,
    (state, action): V1ClickhouseoperatorconfigurationResourceState => ({
      ...state,
      ...action.payload,
      error: null,
      loaded: true
    })
  )
  .handleAction(
    V1ClickhouseoperatorconfigurationActions.fetch.failure,
    (state, action): V1ClickhouseoperatorconfigurationResourceState => ({
      ...state,
      ...action.payload,
      loaded: false
    })
  )
  .handleAction(
    [V1ClickhouseoperatorconfigurationActions.onUpdated, V1ClickhouseoperatorconfigurationActions.onAdded],
    (state, action): V1ClickhouseoperatorconfigurationResourceState => ({
      ...state,
      resources: [
        ...state.resources.filter(
          s => !isSameObject(s, action.payload)
        ),
        action.payload
      ]
    })
  )
  .handleAction(
    V1ClickhouseoperatorconfigurationActions.onDestroyed,
    (state, action): V1ClickhouseoperatorconfigurationResourceState => ({
      ...state,
      resources: state.resources.filter(
        s => !isSameObject(s, action.payload)
      )
    })
  );

export class V1ClickhouseoperatorconfigurationResource extends K8sResource {
  protected api: V1ClickhouseoperatorconfigurationApi;
  protected resource: V1Clickhouseoperatorconfiguration;

  constructor(resource: V1Clickhouseoperatorconfiguration, kubeConfig: KubeConfig) {
    super(resource, kubeConfig);

    this.resource = resource;
    this.api = kubeConfig.makeApiClient(V1ClickhouseoperatorconfigurationApi);
  }
  get spec(): V1Clickhouseoperatorconfiguration {
    return this.resource;
  }
  static startInformer(
    kubeConfig: KubeConfig,
    channel: (input: unknown) => void
  ): () => void {
    const client = kubeConfig.makeApiClient(V1ClickhouseoperatorconfigurationApi);
    let cancelled = false;
    let request: Request;
    //@ts-ignore: error TS7023: 'watch' implicitly has return type 'any'
    const watch = async () => {
      if (cancelled) {
        return;
      }
      try {
        const res = await client.listV1ClickhouseoperatorconfigurationForAllNamespaces();
        channel(
          V1ClickhouseoperatorconfigurationActions.fetch.success({
            resources: res.body.items.map(r => new V1ClickhouseoperatorconfigurationResource(r, kubeConfig))
          })
        );
      } catch (error: any) {
        channel(V1ClickhouseoperatorconfigurationActions.fetch.failure({ error }));
        log.warning("starting informer failed (will retry):  %s", error);
        return setTimeout(watch, 3000);
      }
      const informer = new Watch(kubeConfig);
      const watchHandler = (phase: string, obj: V1Clickhouseoperatorconfiguration) => {
        switch (phase) {
          case "ADDED":
            channel(V1ClickhouseoperatorconfigurationActions.onAdded(new V1ClickhouseoperatorconfigurationResource(obj, kubeConfig)));
            break;
          case "MODIFIED":
            channel(V1ClickhouseoperatorconfigurationActions.onUpdated(new V1ClickhouseoperatorconfigurationResource(obj, kubeConfig)));
            break;
          case "DELETED":
            channel(
              V1ClickhouseoperatorconfigurationActions.onDestroyed(new V1ClickhouseoperatorconfigurationResource(obj, kubeConfig))
            );
            break;
        }
      };
      request = await informer.watch(
        "/apis/clickhouse.altinity.com/v1/clickhouseoperatorconfigurations",
        { resourceVersion: undefined },
        watchHandler,
        watch
      );
      return request;
    };
    watch();
    // Return a function to disable the informer and close the request
    return () => {
      cancelled = true;
      request && request.abort();
    };
  }
  create(): Promise<{
    response: IncomingMessage;
    body: V1Clickhouseoperatorconfiguration;
  }> {
    return this.api.createNamespacedV1Clickhouseoperatorconfiguration(this.namespace, this.resource)

  }
  read(): Promise<{
    response: IncomingMessage;
    body: V1Clickhouseoperatorconfiguration;
  }> {
    return this.api.readNamespacedV1Clickhouseoperatorconfiguration(this.name, this.namespace)

  }
  update(): Promise<{
    response: IncomingMessage;
    body: V1Clickhouseoperatorconfiguration;
  }> {
    return this.api.patchNamespacedV1Clickhouseoperatorconfiguration(
        this.name,
        this.namespace,
        this.resource,
        undefined,
        undefined,
        { headers: { "Content-Type": "application/merge-patch+json" } }
      )

  }
  delete(): Promise<{
    response: IncomingMessage;
    body: V1Status;
  }> {
    return this.api.deleteNamespacedV1Clickhouseoperatorconfiguration(this.name, this.namespace)
  }
}
