tenants:
  - default
env_label: opstrace-ci
cert_issuer: letsencrypt-staging
aws:
  eks_admin_roles:
    - AWSReservedSSO_AdministratorAccess_8488c3da2f880f06
custom_auth0_client_id: 5MoCYfPXPuEzceBLRUr6T6SAklT2GDys
custom_auth0_domain: opstrace-dev.us.auth0.com
