name: Sync Algolia

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"

jobs:
  algolia:
    runs-on: ubuntu-latest
    name: Algolia Sync
    steps:
      - uses: actions/checkout@v2
      - uses: opstrace/algolia-docs-sync@v1.1.0
        with:
          algoliaId: "QTVPN6XDU8"
          algoliaKey: ${{ secrets.ALGOLIA_KEY }}
          algoliaIndex: "opstrace-docs"
  cloudflare:
    runs-on: ubuntu-latest
    name: Rebuild Site
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_PROJECT_ID: opstrace
    steps:
      - run: |
          curl \
            -H "Content-Type: application/json" \
            -H "X-Auth-Email: $CLOUDFLARE_ACCOUNT_EMAIL" \
            -H "X-Auth-Key: $CLOUDFLARE_API_TOKEN" \
            -X POST \
            https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$CLOUDFLARE_PROJECT_ID/deployments
